### ISSUE TITLE
Fail to extract video files

### ISSUE THREAD

**Issue by Liuhaai** [vitrivr/cineast#183]
An error happens when I try to extract features from video files, although Cineast works normally with image files.

> Exception in thread "Thread-7" java.lang.NoSuchMethodError: java.lang.Math.floorDiv(JI)J
        at org.vitrivr.cineast.core.extraction.decode.video.FFMpegVideoDecoder.getFrameTimestamp(FFMpegVideoDecoder.java:211)
        at org.vitrivr.cineast.core.extraction.decode.video.FFMpegVideoDecoder.readVideo(FFMpegVideoDecoder.java:299)
        at org.vitrivr.cineast.core.extraction.decode.video.FFMpegVideoDecoder.readFrame(FFMpegVideoDecoder.java:169)
        at org.vitrivr.cineast.core.extraction.decode.video.FFMpegVideoDecoder.getNext(FFMpegVideoDecoder.java:591)
        at org.vitrivr.cineast.core.extraction.decode.video.FFMpegVideoDecoder.getNext(FFMpegVideoDecoder.java:37)
        at org.vitrivr.cineast.core.extraction.segmenter.video.VideoHistogramSegmenter.queueFrames(VideoHistogramSegmenter.java:288)
        at org.vitrivr.cineast.core.extraction.segmenter.video.VideoHistogramSegmenter.queueFrames(VideoHistogramSegmenter.java:278)
        at org.vitrivr.cineast.core.extraction.segmenter.video.VideoHistogramSegmenter.run(VideoHistogramSegmenter.java:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by Liuhaai** [comment]
This issue is solved by compiling the project using JDK 15
