### ISSUE TITLE
GRPC Endpoint does not start

### ISSUE THREAD

**Issue by silvanheller** [vitrivr/cineast#254]
With the following error message:
```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class 
io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder$NettyClientTransportServersBuilder does not define or inherit an implementation 
of the resolved method 'abstract io.grpc.internal.InternalServer buildClientTransportServers(java.util.List)' of interface 
io.grpc.internal.ServerImplBuilder$ClientTransportServersBuilder.                                     at 
io.grpc.internal.ServerImplBuilder.build(ServerImplBuilder.java:242)                                                                                                                                             
at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:173)                                                                                                                             
at org.vitrivr.cineast.api.GRPCEndpoint.start(GRPCEndpoint.java:32)                                                                                                                                                 
at org.vitrivr.cineast.api.Main.main(Main.java:32)  
```

**Comment by lucaro** [comment]
This appears to be caused by a version conflict in the grpc dependencies. CottontailDB and the cineast endpoint both use a newer version of grpc than adampro. I guess there are two ways to fix this:

1. overwriting the dependencies of the adampro driver such that grpc 1.44 instead of grpc 1.36 is loaded, which might be a hassle and may or may not cause the adampro driver to break
2. remove the adampro driver

Thoughts?

**Comment by ppanopticon** [comment]
I'd vote for removing the ADAMpro driver.

**Comment by lucaro** [comment]
There is if I'm not mistaken. Try `entity dump` via the cottontail cli.

**Comment by silvanheller** [comment]
Ok, thanks to the work of @Spiess and @ppanopticon I can confirm that `entity dump` works fine, so we can remove all ADAMpro code. I'm closing this issue though.
