### ISSUE TITLE
Error in CottontailDB connection if schema does not already exist

### ISSUE THREAD

**Issue by Spiess** [vitrivr/cineast#255]
Starting Cineast connected to a CottontailDB instance without the schema warren.cineast already in the database causes an error with a large stack trace:
```
[main] ERROR o.v.c.c.d.DBSelector - Failed to close TupleIterator!
io.grpc.StatusRuntimeException: NOT_FOUND: [2, 53715eb5-2843-4c78-9ec0-c3058498c443] Execution of null failed: Schema 'warren.cineast' does not exist!
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.grpc.DDLGrpc$DDLBlockingStub.entityDetails(DDLGrpc.java:856) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about$lambda-38$lambda-37(SimpleClient.kt:430) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.Context.call(Context.java:551) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about$lambda-38(SimpleClient.kt:428) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.Context.call(Context.java:551) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about(SimpleClient.kt:426) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about(SimpleClient.kt:440) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.cottontaildb.CottontailSelector.existsEntity(CottontailSelector.java:345) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.dao.reader.TagReader.initCache(TagReader.java:162) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.dao.reader.TagReader.<init>(TagReader.java:55) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.rest.handlers.actions.tag.FindTagsAllGetHandler.<clinit>(FindTagsAllGetHandler.java:16) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.registerRestOperations(APIEndpoint.java:396) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.<init>(APIEndpoint.java:120) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.getInstance(APIEndpoint.java:125) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.Main.main(Main.java:31) [cineast-api-3.7.0-all.jar:1.xx]
```

**Comment by lucaro** [comment]
This is caused by the tag autocomplete handler trying to initialize its cache. This isn't really a bug, the failure case is just not very nicely logged.

**Comment by Spiess** [comment]
In previous versions of cineast, this was not the case, making logging output much easier to read.
If it's not supposed to happen, it's a bug.

**Comment by lucaro** [comment]
> If it's not supposed to happen, it's a bug.

What *is supposed* or *is not supposed* to happen is up for debate. The caching mechanism throws an error which is handled and logged. You might argue that the way it is logged is excessive, and I would grant you that, but this behavior does in no way negatively affect the remaining operation.
