### ISSUE TITLE
Error with large stack trace on startup if no CottontailDB connected

### ISSUE THREAD

**Issue by Spiess** [vitrivr/cineast#256]
Starting Cineast without a CottontailDB connected causes an error with a large stack trace:
```
[main] ERROR o.v.c.c.d.DBSelector - Failed to close TupleIterator!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.grpc.DDLGrpc$DDLBlockingStub.entityDetails(DDLGrpc.java:856) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about$lambda-38$lambda-37(SimpleClient.kt:430) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.Context.call(Context.java:551) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about$lambda-38(SimpleClient.kt:428) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.Context.call(Context.java:551) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about(SimpleClient.kt:426) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about(SimpleClient.kt:440) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.cottontaildb.CottontailSelector.existsEntity(CottontailSelector.java:345) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.dao.reader.TagReader.initCache(TagReader.java:162) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.dao.reader.TagReader.<init>(TagReader.java:55) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.rest.handlers.actions.tag.FindTagsAllGetHandler.<clinit>(FindTagsAllGetHandler.java:16) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.registerRestOperations(APIEndpoint.java:396) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.<init>(APIEndpoint.java:120) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.getInstance(APIEndpoint.java:125) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.Main.main(Main.java:31) [cineast-api-3.7.0-all.jar:1.xx]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:1865
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[cineast-api-3.7.0-all.jar:1.xx]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

**Comment by ppanopticon** [comment]
What else would you expect to happen?

**Comment by Spiess** [comment]
In previous versions of Cineast a warning was logged, making the logging output much easier to read:
```
No config path given, loading default config cineast.json
2022-02-10 11:08:16.828 [main] INFO o.v.c.s.c.Config - Config file loaded!
2022-02-10 11:08:16.833 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to cottontail at localhost:1865
2022-02-10 11:08:16.959 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 11:08:16.970 [main] DEBUG o.v.c.c.d.d.r.TagReader - Tag Reader initialized in 7 ms
```

**Comment by lucaro** [comment]
Not being able to connect to the persistent storage backend is not really a warning, since Cineast won't really be able to do much in that case. The stacktrace is debatable.

**Comment by Spiess** [comment]
Cineast is also a feature extractor, intended to be used standalone to extract features to JSON files, or am I misunderstanding something?

**Comment by Spiess** [comment]
Thank you, this makes sense.
