### ISSUE TITLE
Cineast CLI fails to start

### ISSUE THREAD

**Issue by Spiess** [vitrivr/cineast#257]
On the current master branch, Cineast never reaches the CLI and does not accept any CLI commands.
Possibly caused by #254.

**Comment by lucaro** [comment]
I cannot reproduce this, could you elaborate?

**Comment by Spiess** [comment]
On a clean repository clone, running the shadowJar build cineast-api Jar file no CLI commands can be issued.
Tested on macOS and Linux.

Abbreviated output example (`test` and `help` were entered):
```
...
2022-02-10 11:02:27.729 [main] INFO o.v.c.a.GRPCEndpoint - Starting GRPC Endpoint at port 4570
Exception in thread "main" java.lang.AbstractMethodError: Receiver class io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder$NettyClientTransportServersBuilder does not define or inherit an implementation of the resolved method 'abstract io.grpc.internal.InternalServer buildClientTransportServers(java.util.List)' of interface io.grpc.internal.ServerImplBuilder$ClientTransportServersBuilder.
	at io.grpc.internal.ServerImplBuilder.build(ServerImplBuilder.java:242)
	at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:173)
	at org.vitrivr.cineast.api.GRPCEndpoint.start(GRPCEndpoint.java:32)
	at org.vitrivr.cineast.api.Main.main(Main.java:32)
test
help
^C2022-02-10 11:02:32.814 [Thread-23] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
...
```

**Comment by ppanopticon** [comment]
Indeed if unhandled exceptions stemming from one of the following lines bubble up, then the CLI won't start. Wrapping those in a try...catch would be a solution. However, chances are that if initialisation fails, the CLI will not be able to do useful work either.

```java
      /* Start API endpoint. */
      APIEndpoint.getInstance().start();

      /* Start gRPC endpoint. */
      GRPCEndpoint.start();

      /* Initialize Monitoring */
      PrometheusServer.initialize();
```
