### ISSUE TITLE
Large amounts of Cottontail connection and closing messages

### ISSUE THREAD

**Issue by Spiess** [vitrivr/cineast#258]
Starting Cineast with or without connected Cottontail DB causes large amounts of Cottontail connection messages, either caused by a logging bug or several connections actually being established.
Stopping Cineast causes equally many Connection closing messages to be logged.
```
No config path given, loading default config cineast.json
2022-02-10 09:31:14.322 [main] INFO o.v.c.s.c.Config - Config file loaded!
2022-02-10 09:31:14.337 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.451 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 115 ms at localhost:1865
2022-02-10 09:31:14.583 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.591 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.592 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.598 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.620 [main] ERROR o.v.c.c.d.DBSelector - Failed to close TupleIterator!
io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.grpc.DDLGrpc$DDLBlockingStub.entityDetails(DDLGrpc.java:856) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about$lambda-38$lambda-37(SimpleClient.kt:430) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.Context.call(Context.java:551) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about$lambda-38(SimpleClient.kt:428) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.grpc.Context.call(Context.java:551) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about(SimpleClient.kt:426) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cottontail.client.SimpleClient.about(SimpleClient.kt:440) ~[cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.cottontaildb.CottontailSelector.existsEntity(CottontailSelector.java:345) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.dao.reader.TagReader.initCache(TagReader.java:162) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.core.db.dao.reader.TagReader.<init>(TagReader.java:55) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.rest.handlers.actions.tag.FindTagsAllGetHandler.<clinit>(FindTagsAllGetHandler.java:16) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.registerRestOperations(APIEndpoint.java:396) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.<init>(APIEndpoint.java:120) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.APIEndpoint.getInstance(APIEndpoint.java:125) [cineast-api-3.7.0-all.jar:1.xx]
	at org.vitrivr.cineast.api.Main.main(Main.java:31) [cineast-api-3.7.0-all.jar:1.xx]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/0:0:0:0:0:0:0:1:1865
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777) ~[?:?]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:330) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[cineast-api-3.7.0-all.jar:1.xx]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[cineast-api-3.7.0-all.jar:1.xx]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-02-10 09:31:14.629 [main] DEBUG o.v.c.c.d.d.r.TagReader - Tag Reader initialized in 30 ms
2022-02-10 09:31:14.630 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.631 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.635 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.636 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.636 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.640 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.642 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.643 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.646 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.647 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.648 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.651 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.681 [main] INFO o.e.j.u.log - Logging initialized @1100ms to org.eclipse.jetty.util.log.Slf4jLog
2022-02-10 09:31:14.926 [main] WARN o.e.j.s.h.AbstractHandler - No Server set for ConfigurableHandler@2630dbc4{STARTING}
2022-02-10 09:31:14.936 [main] WARN o.e.j.s.h.AbstractHandler - No Server set for ConfigurableHandler@72fd8a3c{STARTING}
2022-02-10 09:31:14.943 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.943 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.947 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.947 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.948 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.951 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.952 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.952 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.955 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.956 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.956 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.959 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.962 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.962 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.965 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.966 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.966 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.968 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.969 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.969 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.972 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.972 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.973 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.976 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.976 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.977 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.980 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.980 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.981 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.984 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.985 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.985 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.988 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.989 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.989 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.992 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.993 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.994 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:14.997 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:14.997 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:14.997 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:15.000 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:15.001 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:15.001 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:15.003 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:15.004 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:15.004 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:15.006 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:15.037 [main] DEBUG o.v.c.c.d.c.CottontailWrapper - Starting to connect to Cottontail DB at localhost:1865
2022-02-10 09:31:15.038 [main] INFO o.v.c.c.d.c.CottontailWrapper - Connected to Cottontail DB in 0 ms at localhost:1865
2022-02-10 09:31:15.041 [main] WARN o.v.c.c.d.c.CottontailWrapper - Could not connect to Cottontail at localhost:1865
2022-02-10 09:31:15.078 [main] INFO o.e.j.s.Server - jetty-9.4.44.v20210927; built: 2021-09-27T23:02:44.612Z; git: 8da83308eeca865e495e53ef315a249d63ba9332; jvm 11.0.13+8-Ubuntu-0ubuntu1.20.04
2022-02-10 09:31:15.116 [main] INFO o.e.j.s.AbstractConnector - Started ServerConnector@551de37d{HTTP/1.1, (http/1.1)}{0.0.0.0:4567}
2022-02-10 09:31:15.117 [main] INFO o.e.j.s.Server - Started @1537ms
2022-02-10 09:31:15.117 [main] INFO o.v.c.a.GRPCEndpoint - Starting GRPC Endpoint at port 4570
Exception in thread "main" java.lang.AbstractMethodError: Receiver class io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder$NettyClientTransportServersBuilder does not define or inherit an implementation of the resolved method 'abstract io.grpc.internal.InternalServer buildClientTransportServers(java.util.List)' of interface io.grpc.internal.ServerImplBuilder$ClientTransportServersBuilder.
	at io.grpc.internal.ServerImplBuilder.build(ServerImplBuilder.java:242)
	at io.grpc.internal.AbstractServerImplBuilder.build(AbstractServerImplBuilder.java:173)
	at org.vitrivr.cineast.api.GRPCEndpoint.start(GRPCEndpoint.java:32)
	at org.vitrivr.cineast.api.Main.main(Main.java:32)
^C2022-02-10 09:31:19.270 [Thread-12] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.271 [Thread-10] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.271 [Thread-1] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.270 [Thread-15] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.271 [Thread-18] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.271 [Thread-3] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.272 [Thread-11] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.272 [Thread-19] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.273 [Thread-4] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.273 [Thread-8] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.275 [Thread-14] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.275 [Thread-13] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.276 [Thread-23] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.276 [Thread-22] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.277 [Thread-0] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.277 [Thread-17] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.279 [Thread-2] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.279 [Thread-7] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.279 [Thread-21] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.279 [Thread-9] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.280 [Thread-16] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.280 [Thread-5] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
2022-02-10 09:31:19.281 [Thread-20] INFO o.v.c.c.d.c.CottontailWrapper - Closing connection to Cottontail DB.
```

**Comment by Spiess** [comment]
The many connection messages appear to come from most API endpoints opening their own DB connection channel through `Config.sharedConfig().getDatabase().getSelectorSupplier().get()`. Is this intended behavior or should they all be sharing one connection?
