### ISSUE TITLE
Failed  to start http endpoint due to exception 

### ISSUE THREAD

**Issue by mamoudmatook** [vitrivr/cineast#88]
Hello, supporters, 
cineast was working fine with me 2 weeks ago, but I decided to  trigger 
`git pull origin master` to keep me up-to-date and the I recompiled cineast so a new exception related to Jetty server appeared, I'm not sure if _Jetty was there from the beginning_ I think apache was used as web server below is the stack trace I hope you could help me.

`2019-08-31 19:32:32.669 [main] WARN o.v.c.c.c.d.FeatureCategoriesDeserializer - The specified feature 'QueryImageExporter' could not be instantiated: java.lang.ClassNotFoundException: org.vitrivr.cineast.core.features.QueryImageExporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.vitrivr.cineast.core.util.ReflectionHelper.getClassFromName(ReflectionHelper.java:449)
	at org.vitrivr.cineast.core.config.deserializers.FeatureCategoriesDeserializer.deserialize(FeatureCategoriesDeserializer.java:58)
	at org.vitrivr.cineast.core.config.deserializers.FeatureCategoriesDeserializer.deserialize(FeatureCategoriesDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
	at org.vitrivr.cineast.core.util.json.JacksonJsonProvider.toObject(JacksonJsonProvider.java:70)
	at org.vitrivr.cineast.core.config.Config.loadConfig(Config.java:53)
	at org.vitrivr.cineast.core.config.Config.sharedConfig(Config.java:42)
	at org.vitrivr.cineast.monitoring.PrometheusServer.initialize(PrometheusServer.java:29)
	at org.vitrivr.cineast.api.API.main(API.java:90)

2019-08-31 19:32:32.693 [main] WARN o.v.c.c.c.d.FeatureCategoriesDeserializer - The specified feature 'SubtitleWordSearch' could not be instantiated: java.lang.ClassNotFoundException: org.vitrivr.cineast.core.features.SubtitleWordSearch
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.vitrivr.cineast.core.util.ReflectionHelper.getClassFromName(ReflectionHelper.java:449)
	at org.vitrivr.cineast.core.config.deserializers.FeatureCategoriesDeserializer.deserialize(FeatureCategoriesDeserializer.java:58)
	at org.vitrivr.cineast.core.config.deserializers.FeatureCategoriesDeserializer.deserialize(FeatureCategoriesDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2890)
	at org.vitrivr.cineast.core.util.json.JacksonJsonProvider.toObject(JacksonJsonProvider.java:70)
	at org.vitrivr.cineast.core.config.Config.loadConfig(Config.java:53)
	at org.vitrivr.cineast.core.config.Config.sharedConfig(Config.java:42)
	at org.vitrivr.cineast.monitoring.PrometheusServer.initialize(PrometheusServer.java:29)
	at org.vitrivr.cineast.api.API.main(API.java:90)

2019-08-31 19:32:32.695 [main] INFO o.v.c.c.c.Config - Config file loaded!
2019-08-31 19:32:32.695 [main] INFO o.v.c.m.PrometheusServer - Prometheus monitoring not enabled
Starting HTTP API...
Cineast CLI started.
2019-08-31 19:32:32.947 [Thread-2] INFO o.e.j.u.log - Logging initialized @3926ms to org.eclipse.jetty.util.log.Slf4jLog
2019-08-31 19:32:34.049 [Thread-2] INFO o.e.j.s.Server - jetty-9.4.z-SNAPSHOT
2019-08-31 19:32:34.083 [Thread-2] FATAL o.v.c.a.APIEndpoint - Failed to start HTTP endpoint due to an exception. Cineast will shut down now!
java.lang.IllegalStateException: Insufficient threads: max=8 < needed(acceptors=1 + selectors=8 + request=1)
	at org.eclipse.jetty.server.Server.doStart(Server.java:414) ~[cineast.jar:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68) ~[cineast.jar:?]
	at spark.embeddedserver.jetty.EmbeddedJettyServer.ignite(EmbeddedJettyServer.java:149) ~[cineast.jar:?]
	at spark.Service.lambda$init$2(Service.java:496) ~[cineast.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
`

**Comment by lucaro** [comment]
Hey,

jetty has always been the server used by cineast to provide the HTTP API. You can use apache or any other web server to serve content in addition if that makes sense for your deployment.

Your log output shows several problems:
1. you are using feature modules which no longer exist. Just remove the QueryImageExporter and SubtitleWordSearch from your config.
2. The thread pool for jetty is too small. You can increase this in the config as well.

**Comment by mamoudmatook** [comment]
Hello, thanks for your support 
which config file i should increase thread pool as in cineast.config nothing there related to jetty

**Comment by lucaro** [comment]
The relevant value is `threadPoolSize` in the `api` block.

**Comment by mamoudmatook** [comment]
Hello Lucaro, I could see that treadPoolSize is inside 

1. APIConfig.java  >> private int threadPoolSize = 8
2. RetrieverConfig.java >>  private int threadPoolSize = 4;
so which one of the above?
is there any other  .json file  I could change this value into it so I won't have to recompile.

**Comment by lucaro** [comment]
All configuration is done in the `cineast.json` file, there is no need to change the code. See https://github.com/vitrivr/cineast/blob/master/cineast.json

**Comment by mamoudmatook** [comment]
Thanks a lot  :)
