### ISSUE TITLE
Connection Issue when I implemented in Docker

### ISSUE THREAD

**Issue by nxh235** [vitrivr/cineast#93]
I followed this guide (https://vitrivr.org/getting_started.html) to run AdamPro in Docker in 3 ports (8080, 5890 and 443) using this command in **Ubuntu 18.04**:
`docker run --name adampro -p 8080:4040 -p 5890:5890 -p 443:9099 -d vitrivr/adampro:2.1-selfcontained`

Next, I executed `java -jar cineast.jar --setup` and running the extraction successfully.
**vitrivr-ng** is configured in **nginx 1.14.0** through port **80**.

When I run the command below, the error message show on the screen.
`java -jar cineast.jar`

**Error message:**

~~~
root@ubuntu: java -jar cineast.jar
2019-11-13 15:51:16.007 [main] INFO o.v.c.c.c.Config - Config file loaded!
2019-11-13 15:51:16.029 [main] INFO o.v.c.m.PrometheusServer - Initalizing Prometheus endpoint at port 4569
2019-11-13 15:51:16.061 [main] INFO o.e.j.u.log - Logging initialized @1291ms to org.eclipse.jetty.util.log.Slf4jLog
2019-11-13 15:51:16.141 [main] INFO o.v.c.m.PrometheusExtractionTaskMonitor - Initalizing Prometheus Extraction Task Monitor
2019-11-13 15:51:16.144 [main] INFO o.v.c.m.ImportTaskMonitor - Initalizing Prometheus Extraction Task Monitor
2019-11-13 15:51:16.144 [main] INFO o.v.c.m.DatabaseHealthMonitor - Initalizing Prometheus Extraction Task Monitor
2019-11-13 15:51:16.678 [main] INFO o.v.c.m.RetrievalTaskMonitor - Initalizing Prometheus Retrieval Task Monitor
2019-11-13 15:51:16.681 [main] INFO o.e.j.s.Server - jetty-9.4.z-SNAPSHOT
2019-11-13 15:51:16.737 [main] INFO o.e.j.s.h.ContextHandler - Started o.e.j.s.ServletContextHandler@70a36a66{/,null,AVAILABLE}
2019-11-13 15:51:16.751 [main] INFO o.e.j.s.AbstractConnector - Started ServerConnector@23bff419{HTTP/1.1,[http/1.1]}{0.0.0.0:4569}
2019-11-13 15:51:16.751 [main] INFO o.e.j.s.Server - Started @1985ms
Starting HTTP API...
Cineast CLI started.
2019-11-13 15:51:16.888 [Thread-13] INFO o.e.j.s.Server - jetty-9.4.z-SNAPSHOT
2019-11-13 15:51:16.903 [Thread-13] INFO o.e.j.s.session - DefaultSessionIdManager workerName=node0
2019-11-13 15:51:16.904 [Thread-13] INFO o.e.j.s.session - No SessionScavenger set, using defaults
2019-11-13 15:51:16.905 [Thread-13] INFO o.e.j.s.session - Scavenging every 660000ms
2019-11-13 15:51:16.909 [Thread-13] INFO o.e.j.s.h.ContextHandler - Started o.e.j.s.ServletContextHandler@48f3e9e9{/,null,AVAILABLE}
2019-11-13 15:51:16.914 [Thread-13] INFO o.e.j.s.AbstractConnector - Started ServerConnector@37312d7a{HTTP/1.1,[http/1.1]}{0.0.0.0:4567}
2019-11-13 15:51:16.914 [Thread-13] INFO o.e.j.s.Server - Started @2148ms
2019-11-13 15:51:17.112 [Thread-1] ERROR o.v.c.c.d.a.ADAMproWrapper - error in pingBlocking: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: AdamSearch/Ping
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:528)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:509)
        at org.vitrivr.cineast.core.db.adampro.ADAMproWrapper.pingBlocking(ADAMproWrapper.java:108)
        at org.vitrivr.cineast.core.db.adampro.AbstractADAMproSelector.ping(AbstractADAMproSelector.java:164)
        at org.vitrivr.cineast.monitoring.DatabaseHealthMonitor.lambda$init$0(DatabaseHealthMonitor.java:38)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: AdamSearch/Ping
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:433)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:339)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:107)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more

2019-11-13 15:51:17.113 [Thread-1] ERROR o.v.c.m.DatabaseHealthMonitor - Connection issue, waiting for 1 minute
HTTP API started!
2019-11-13 15:52:19.152 [Thread-1] ERROR o.v.c.c.d.a.ADAMproWrapper - error in pingBlocking: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: AdamSearch/Ping
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:528)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:509)
        at org.vitrivr.cineast.core.db.adampro.ADAMproWrapper.pingBlocking(ADAMproWrapper.java:108)
        at org.vitrivr.cineast.core.db.adampro.AbstractADAMproSelector.ping(AbstractADAMproSelector.java:164)
        at org.vitrivr.cineast.monitoring.DatabaseHealthMonitor.lambda$init$0(DatabaseHealthMonitor.java:38)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNIMPLEMENTED: Method not found: AdamSearch/Ping
        at io.grpc.Status.asRuntimeException(Status.java:526)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:433)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:339)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:107)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more

2019-11-13 15:52:19.153 [Thread-1] ERROR o.v.c.m.DatabaseHealthMonitor - Connection issue, waiting for 1 minute
~~~

`netstat -tulpn`, port 80, 443, 80, 5890, 4567 and 4569 are in use but **vitrivr-ng** cannot connect to **cineast**.

![image](https://user-images.githubusercontent.com/33388326/68778940-7229e300-0666-11ea-8390-5112e34ff853.png)

API port in **config.json** in vitrivr-ng:

~~~
"api": {
    "host" : "127.0.0.1",
    "port" : 4567,
    "protocol_http": "http",
    "protocol_ws": "ws",
    "ping_interval": 10000
  }
~~~

Error in Chrome:

![image](https://user-images.githubusercontent.com/33388326/68780678-37757a00-0669-11ea-9355-6cf613d887d9.png)

I hope for you help! Thank you very much!

**Comment by lucaro** [comment]
Hey, it looks like you have two separate problems there. The first appears to be a version mismatch between ADAMpro and cineast. Which version of cineast are you using?

The second is the connection between cineast and the front end, which you should be able to establish even if the connection between ADAMpro and cineast does not work properly. In your config.json, you specify localhost as host for cineast. Are you running the whole vitrivr stack on the same machine as you opened your browser window?

**Comment by nxh235** [comment]
> Hey, it looks like you have two separate problems there. The first appears to be a version mismatch between ADAMpro and cineast. Which version of cineast are you using?
> 
> The second is the connection between cineast and the front end, which you should be able to establish even if the connection between ADAMpro and cineast does not work properly. In your config.json, you specify localhost as host for cineast. Are you running the whole vitrivr stack on the same machine as you opened your browser window?

For the first problem, I use ADAMPro 2.1 and the latest code of cineast (pull from GitHub).

The second one, I run the whole vitrivr stack in a virtual machine, then I connect to its via SSH and OpenVPN, but the OpenVPN allows only port 80, 8080 and 443. I don't know how to access another port in the virtual machine via OpenVPN.

**Comment by lucaro** [comment]
Just to clarify, you pulled from and subsequently compiled the master branch of cineast? If so, this is indeed a problem we will investigate internally. As for the other issue, the way you currently configured cineast and vitrivr-ng is to use port 4567 for the web socket/REST API connection. In case that port is not accessible to you, you could either proxy this connection through your nginx instance or, simply set both to use port 8080. To do so, change the port in both `cineast.json` for cineast and `config.json` for the UI to 8080 and, additionally in the config for the UI, set the "host" field to the address of the server you are using. This should at least take care of the second issue, I'll update you on the first as soon as we have identified the problem internally.

**Comment by nxh235** [comment]
> Just to clarify, you pulled from and subsequently compiled the master branch of cineast? If so, this is indeed a problem we will investigate internally. As for the other issue, the way you currently configured cineast and vitrivr-ng is to use port 4567 for the web socket/REST API connection. In case that port is not accessible to you, you could either proxy this connection through your nginx instance or, simply set both to use port 8080. To do so, change the port in both `cineast.json` for cineast and `config.json` for the UI to 8080 and, additionally in the config for the UI, set the "host" field to the address of the server you are using. This should at least take care of the second issue, I'll update you on the first as soon as we have identified the problem internally.

I tried AdamPRO 2.1 and cineast 2.0. Everything seems to be working correctly till I run the command `java -jar cineast.jar` and receive this message:
~~~
root@ubuntu:/home/cineast-2.0.0/build/libs# java -jar cineast.jar
06:53:39.623 [main] INFO  org.vitrivr.cineast.core.config.Config - Config file loaded!
Starting HTTP API...
Cineast CLI started.
06:53:39.689 [Thread-2] INFO  org.eclipse.jetty.util.log - Logging initialized @1154ms
Nov 16, 2019 6:53:40 AM io.grpc.internal.ManagedChannelImpl <init>
INFO: [ManagedChannelImpl@5f0657e5] Created with target 127.0.0.1:5890
06:53:40.281 [Thread-2] INFO  org.eclipse.jetty.server.Server - jetty-9.3.z-SNAPSHOT
root@ubuntu:/home/cineast-2.0.0/build/libs#
~~~
Cineast exited. I don't know why. Please help me. Thanks.

**Comment by lucaro** [comment]
If I understand you correctly, you get that 404 while trying to access the cineast HTTP API directly from your web browser via `http://<server>:<port>/` , correct? In this case, this response is to be expected. By default, cineast only responds to API requests and not to anything else. While cineast can be used to serve the UI directly, it makes more to use a more efficient web server like nginx. Since the HTTP API is accessible to you at all (otherwise you wouldn't get an error but a time out) you should now be able to connect the UI to it by setting the UI `config.json` to the same host and port which you used to get that 404 in your browser.

**Comment by nxh235** [comment]
> If I understand you correctly, you get that 404 while trying to access the cineast HTTP API directly from your web browser via `http://<server>:<port>/` , correct? In this case, this response is to be expected. By default, cineast only responds to API requests and not to anything else. While cineast can be used to serve the UI directly, it makes more to use a more efficient web server like nginx. Since the HTTP API is accessible to you at all (otherwise you wouldn't get an error but a time out) you should now be able to connect the UI to it by setting the UI `config.json` to the same host and port which you used to get that 404 in your browser.

I had already solved the problem. I’m extremely grateful for you. Thank you so much.

**Comment by lucaro** [comment]
Great to hear that it works! Would you have any suggestions on how to make the 'getting started' guide clearer in order to avoid the problems you encountered in the future?

**Comment by hoangphuc1998** [comment]
@nxh235 Can you tell me which versions did you use exactly? I have tried multiple combinations but nothing works
